// <auto-generated />
namespace VirtualWellnessProgram.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedapplicationuserforeignkeytocustomer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedapplicationuserforeignkeytocustomer));
        
        string IMigrationMetadata.Id
        {
            get { return "201711012025342_added application user foreign key to customer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
