// <auto-generated />
namespace WellnessProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedpendingandday : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedpendingandday));
        
        string IMigrationMetadata.Id
        {
            get { return "201710302208379_added pending and day"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
